title: "Lucia Elizabeth Donatelli"
author: "Lucia Donatelli"
description: "Vrije Universiteit Amsterdam"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false      # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "research.md", title: "Research"}
  - {title: "CV", file: "CV.md"}
  - {title: "Teaching", file: "teaching.md"}
  - {title: "Students", file: "students.md"}
  - {title: "Sport", file: "sport.md"}
  - {title: "Contact", file: "contact.md"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:l.e.donatelli@vu.nl"}
  - {title: Github, icon: github, url: "https://github.com/cltl"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/lucia_elizabe"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
